src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Naam;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Uitgiftes::class, mappedBy="MedewerkerNaam")
     */
    private $uitgiftes;

    /**
     * @ORM\OneToMany(targetEntity=Innames::class, mappedBy="MedewerkerNaam")
     */
    private $innames;

    public function __construct()
    {
        $this->uitgiftes = new ArrayCollection();
        $this->innames = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->Naam;
    }

    public function setNaam(string $Naam): self
    {
        $this->Naam = $Naam;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Uitgiftes[]
     */
    public function getUitgiftes(): Collection
    {
        return $this->uitgiftes;
    }

    public function addUitgifte(Uitgiftes $uitgifte): self
    {
        if (!$this->uitgiftes->contains($uitgifte)) {
            $this->uitgiftes[] = $uitgifte;
            $uitgifte->setMedewerkerNaam($this);
        }

        return $this;
    }

    public function removeUitgifte(Uitgiftes $uitgifte): self
    {
        if ($this->uitgiftes->removeElement($uitgifte)) {
            // set the owning side to null (unless already changed)
            if ($uitgifte->getMedewerkerNaam() === $this) {
                $uitgifte->setMedewerkerNaam(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Innames[]
     */
    public function getInnames(): Collection
    {
        return $this->innames;
    }

    public function addInname(Innames $inname): self
    {
        if (!$this->innames->contains($inname)) {
            $this->innames[] = $inname;
            $inname->setMedewerkerNaam($this);
        }

        return $this;
    }

    public function removeInname(Innames $inname): self
    {
        if ($this->innames->removeElement($inname)) {
            // set the owning side to null (unless already changed)
            if ($inname->getMedewerkerNaam() === $this) {
                $inname->setMedewerkerNaam(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNaam();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('/css/styles.css')}}">
            <!-- CSS only -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
            <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
            <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-light-green.css">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% endblock %}

        <!-- Sidebar -->
        <nav class="w3-sidebar w3-bar-block w3-collapse w3-animate-left w3-card" style="z-index:3;width:250px;" id="mySidebar">
            <a class="w3-bar-item w3-button w3-border-bottom w3-large" href="/"><img src="https://pngimg.com/uploads/recycle/recycle_PNG32.png" style="width:80%;"></a>
            <a class="w3-bar-item w3-button w3-hide-large w3-large" href="javascript:void(0)" onclick="w3_close()">Close <i class="fa fa-remove"></i></a>
            <a class="w3-bar-item w3-button w3-light-green" href="/">Home</a>
            <a class="w3-bar-item w3-button" href="#">Inname</a>
            <a class="w3-bar-item w3-button" href="#">Verwerking</a>
            <a class="w3-bar-item w3-button" href="#">Uitgifte</a>
            <a class="w3-bar-item w3-button" href="#">Rapportage</a>

            <!-- Drop-down in sidebar -->
            <div>
                <a class="w3-bar-item w3-button" onclick="myAccordion('demo')" href="javascript:void(0)">Onderhoud (Admin)<i class="fa fa-caret-down"></i></a>
                <div id="demo" class="w3-hide">
                    <a class="w3-bar-item w3-button" href="/user">Medewerkers</a>
                    <a class="w3-bar-item w3-button" href="/apparaten">Apparaten</a>
                    <a class="w3-bar-item w3-button" href="/onderdelen">Onderdelen</a>
                    <a class="w3-bar-item w3-button" href="/innames">Innames</a>
                    <a class="w3-bar-item w3-button" href="/uitgiftes">Uitgiftes</a>
                </div>
            </div>
        </nav>

        <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" id="myOverlay"></div>

        <div class="w3-main" style="margin-left:250px;">


            <div id="myTop" class="w3-container w3-top w3-theme w3-large">
                <p><i class="fa fa-bars w3-button w3-light-green w3-hide-large w3-xlarge" onclick="w3_open()"></i>
                    <span id="myIntro" class="w3-hide">ReMaS</span></p>
            </div>

            <!-- Remas tekst met versienummer en logout button bovenaan de pagina -->
            <header class="w3-container w3-theme" style="padding:64px 32px">
                <h1 class="w3-xxxlarge">ReMaS Superior Waste Recycling</h1>
                <p>versie: 1.00</p>
                {% if app.user %}
                    <div class="mb-3">
                        Welkom {{ app.user.naam }},
                        <a href="{{ path('app_logout') }}">
                            <img src="https://i.ibb.co/gT1rQ3w/Graphicloads-100-Flat-2-Inside-logout.png"
                                 class="logout w3-hover-sepia">
                        </a>
                    </div>
                    {% else %}
                        <a href="/login">login</a>
                {% endif %}
            </header>

            <div class="w3-container" style="padding:32px">

        {% block javascripts %}
            <!-- JavaScript Bundle with Popper -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
            <script>
                // Open and close the sidebar on medium and small screens
                function w3_open() {
                    document.getElementById("mySidebar").style.display = "block";
                    document.getElementById("myOverlay").style.display = "block";
                }

                function w3_close() {
                    document.getElementById("mySidebar").style.display = "none";
                    document.getElementById("myOverlay").style.display = "none";
                }

                // Change style of top container on scroll
                window.onscroll = function() {myFunction()};
                function myFunction() {
                    if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
                        document.getElementById("myTop").classList.add("w3-card-4", "w3-animate-opacity");
                        document.getElementById("myIntro").classList.add("w3-show-inline-block");
                    } else {
                        document.getElementById("myIntro").classList.remove("w3-show-inline-block");
                        document.getElementById("myTop").classList.remove("w3-card-4", "w3-animate-opacity");
                    }
                }

                // Accordions
                function myAccordion(id) {
                    var x = document.getElementById(id);
                    if (x.className.indexOf("w3-show") == -1) {
                        x.className += " w3-show";
                        x.previousElementSibling.className += " w3-theme";
                    } else {
                        x.className = x.className.replace("w3-show", "");
                        x.previousElementSibling.className =
                            x.previousElementSibling.className.replace(" w3-theme", "");
                    }
                }
            </script>
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</div>
    <footer class="w3-container w3-theme" style="padding:32px">
        <p>Copyright 2021 - Green</p>
    </footer>
</html>